#!/usr/bin/env bash

set -e

go test ./prettyJson/.

rm -rf out

function build() {
    cpus=$(getconf _NPROCESSORS_ONLN)

    out_dir="out/$1/$2"
    mkdir -p "$out_dir"
    GOOS=$1 GOARCH=$2 \
        go build \
        -ldflags "-X main.AppVersion=0.0.1 -X 'prettyJson.AppBuildTime=$(date)'" \
        -ldflags="-s -w" \
        -p "$cpus" \
        -trimpath \
        -o "$out_dir" \
        ./...
}

build windows amd64
build darwin amd64
build linux amd64

pushd out >/dev/null || :
zip -qq -r prettyJson.zip *
popd >/dev/null || :
