#!/usr/bin/env bash

set -e

go test ./prettyJson/.

rm -rf out

function build() {
    out_dir="out/$1/$2"
    mkdir -p "$out_dir"
    GOOS=$1 GOARCH=$2 \
        go build \
        -ldflags="-s -w" \
        -gcflags=all=-trimpath="$PWD" \
        -asmflags=all=-trimpath="$PWD" \
        -o "$out_dir" \
        ./...
}

build windows 386
build darwin amd64
build linux amd64

pushd out >/dev/null || :
zip -qq -r prettyJson.zip *
popd >/dev/null || :
