#!/usr/bin/env bash

set -e

go test ./...

rm -rf out

VERSION=1.0.4

function build() {
    cpus=$(getconf _NPROCESSORS_ONLN)

    top_level="$(git rev-parse --show-toplevel)"
    out_dir="out/$1/$2"
    mkdir -p "$top_level/$out_dir"

    GOOS=$1 GOARCH=$2 \
        go build \
        -ldflags "-s -w -X main.AppVersion=${VERSION} -X 'main.AppBuildTime=$(date)'" \
        -p "$cpus" \
        -trimpath \
        -o "$top_level/$out_dir" \
        ./...
}

build windows amd64
build darwin amd64
build linux amd64

pushd out >/dev/null || :
zip -qq -r prettyJson.zip *
popd >/dev/null || :
