name: Build and publish
on:
  release:
    types: [created]
jobs:
  run-build-then-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build go binaries
        uses: skx/github-action-build@master
      - uses: actions/upload-artifact@main
        with:
          name: github governance artifacts
          path: out/**/prettyJson
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          releaseId: 0.1
          args: out/darwin/amd64/prettyJson out/linux/amd64/prettyJson out/windows/386/prettyJson