name: Build and publish
on:
  push:
    branches: [ '*' ]
jobs:
  run-build-then-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'
      - run: go version
      - name: build go binaries
        uses: skx/github-action-build@master
        with:
          builder: .github/build.sh
      - uses: actions/upload-artifact@main
        with:
          name: github governance artifacts
          path: out/**/prettyJson
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          args: out/**/prettyJson